services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR: backend
        APP_PORT: 8081
    ports:
      - "8081:8081"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR: frontend
        APP_PORT: 8082
    ports:
      - "8082:8082"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
